server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ameyzing-deshmukh/ECommerceMSApp/tree/feature/spring-cloud-config-changes/cloud-config-files